### PR TITLE
Move `main` function into __main__.py

### PR DESCRIPTION
**Pull request by darthtrevino**
This just cleans up the CLI file a bit

### CODE REVIEW

**Comment by raulgomis** [comment]
Hi @darthtrevino , thanks for your contribution. 

There are some changes required to make it work with the current implementation. 

Change entrypoint to `setup.py`

```
    entry_points={
        'console_scripts': [
            'semversioner = semversioner.__main__:main'
        ]
    },
```

Change `__main__.py` to:

```
from .cli import cli


def main() -> None:
    cli()


if __name__ == "__main__":
    main()
```

Also, please add a changeset file so that we can release it. I'll merge this before your other PR to move everything to Poetry build system.

Thanks!

**Comment by darthtrevino** [comment]
Sounds great, the PR has been updated

**Comment by raulgomis** [comment]
Thanks @darthtrevino ! 👍 Can you also add the changeset file?

**Comment by darthtrevino** [comment]
> Thanks @darthtrevino ! 👍 Can you also add the changeset file?

Yep, just added

**Pull request merged**
